/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import BLL.loadTable;
import static GUI.CaSi_Frame.sql;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author DELL
 */
public class ThongKe_Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame
     */
//    SELECT nhacung
//    .nhacung_id , nhacung
//    .nhacung_ten , donhang
//    .donhang_ngay FROM nhacung INNER JOIN donhang
//ON nhacung
//    .nhacung_id  = donhang.nhacung_id;
    public static String sql = "SELECT nhacsi.MANS, nhacsi.TENNS, baihat.NAMST\n, baihat.TENBH\n"
            + "FROM nhacsi\n"
            + "INNER JOIN baihat\n"
            + "ON nhacsi.MANS = baihat.MANS;";
    public static String maCS; // biến tạm lưu lại MaCS tại dòng có con trỏ chuột click

    public ThongKe_Frame() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

        loadTable.loadData(sql, jtbThongKe);
        loadThongKe();
    }

    public void loadThongKe() {
        loadTable.loadData(sql, jtbThongKe);
        this.countCaSi.setText("Tổng số nhạc sĩ: " + this.jtbThongKe.getRowCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbThongKe = new javax.swing.JTable();
        countCaSi = new javax.swing.JLabel();
        btnIn = new com.k33ptoo.components.KButton();
        btnSX = new com.k33ptoo.components.KButton();

        setPreferredSize(new java.awt.Dimension(920, 490));

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 204, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Thống kê");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_micro_36px.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_micro_36px.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 36, -1, -1));

        jtbThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbThongKeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbThongKe);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 880, 172));

        countCaSi.setText("Số Lượng Ca Sĩ");
        kGradientPanel1.add(countCaSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        btnIn.setText("IN");
        btnIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIn.setkEndColor(new java.awt.Color(0, 153, 153));
        btnIn.setkHoverEndColor(new java.awt.Color(102, 255, 102));
        btnIn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnIn.setkHoverStartColor(new java.awt.Color(255, 102, 153));
        btnIn.setkPressedColor(new java.awt.Color(51, 51, 51));
        btnIn.setkStartColor(new java.awt.Color(0, 102, 102));
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 80, 40));

        btnSX.setText("Sắp Xếp");
        btnSX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSX.setkEndColor(new java.awt.Color(153, 153, 153));
        btnSX.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnSX.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnSX.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        btnSX.setkStartColor(new java.awt.Color(0, 102, 102));
        btnSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSX, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbThongKeMouseClicked
        // TODO add your handling code here:
//        try {
//            int row = this.jtbCaSi.getSelectedRow(); // lấy dòng tại con trỏ chuột
//            String IDrow = (this.jtbCaSi.getModel().getValueAt(row, 0)).toString();// Lấy giá trị tại con trỏ chuột theo kiểu string
//            String sql1 = "select * from CASI where MACS=N'" + IDrow + "'";
//            ResultSet rs = loadTable.showTextField(sql1);
//            // đọc dữ liệu tại dòng "IDrow"
//            if (rs.next()) // nếu có dữ liệu
//            {
//                maCS = rs.getString("MaCS");
//                this.txtMaCS.setText(rs.getString("MaCS"));
//                this.txtTenCS.setText(rs.getString("TenCS"));
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_jtbThongKeMouseClicked

    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException ioe) {
            System.out.println(ioe);
        }
    }
    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();

            if(saveFile != null){
                saveFile = new File(saveFile.toString()+".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("danh sách");
                Row rowCol = sheet.createRow(0);
                for(int i=0;i<jtbThongKe.getColumnCount();i++){
                    Cell cell = rowCol.createCell(i);
                    cell.setCellValue(jtbThongKe.getColumnName(i));
                }
                for(int j=0;j<jtbThongKe.getRowCount();j++){
                    Row row = sheet.createRow(j+1);
                    for(int k=0;k<jtbThongKe.getColumnCount();k++){
                        Cell cell = row.createCell(k);
                        if(jtbThongKe.getValueAt(j, k)!=null){
                            cell.setCellValue(jtbThongKe.getValueAt(j, k).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());
            }else{
                JOptionPane.showMessageDialog(null,"lỗi");
            }
        }catch(FileNotFoundException e){
            System.out.println(e);
        }catch(IOException io){
            System.out.println(io);
        }
    }//GEN-LAST:event_btnInActionPerformed

    private void btnSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT nhacsi.MANS, nhacsi.TENNS, baihat.NAMST\n, baihat.TENBH\n"
            + "FROM nhacsi\n"
            + "INNER JOIN baihat\n"
            + "ON nhacsi.MANS = baihat.MANS ORDER BY MANS"; //lay du lieu
        loadTable.loadData(sql, jtbThongKe);
    }//GEN-LAST:event_btnSXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnIn;
    private com.k33ptoo.components.KButton btnSX;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JLabel countCaSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbThongKe;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
