/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import BLL.MyFunctinon;
import BLL.loadTable;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.SimpleFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author DELL
 */
public class TTBieuDien_Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CaSi_Frame
     */
    public static String sql = "Select * From thongtinbieudien";
    public static String maBD; // biến tạm lưu lại maBD tại dòng có con trỏ chuột click

    public TTBieuDien_Frame() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        //countCaSi.setText("Số lượng ca sĩ : " + Integer.toString(MyFunctinon.countData("CASI")));
        loadTable.loadData(sql, jtbTTBieuDien);
        loadBD();
        loadCbbCaSi();
        loadCbbBH();

    }
    public void loadCbbCaSi() {

        String sql = "SELECT * FROM `casi`";
        try {
            Connection conn = DAL.DataBase.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                this.cbbMaCS.addItem(rs.getString("MACS"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void loadCbbBH() {

        String sql = "SELECT * FROM `baihat`";
        try {
            Connection conn = DAL.DataBase.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                this.cbbMaBH.addItem(rs.getString("MABH"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void loadBD() {
        loadTable.loadData(sql, jtbTTBieuDien);
        this.countBD.setText("Tổng số show diễn: " + this.jtbTTBieuDien.getRowCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTTBieuDien = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtMaBD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        countBD = new javax.swing.JLabel();
        btnXoaTrang = new com.k33ptoo.components.KButton();
        btnThem = new com.k33ptoo.components.KButton();
        btnSua = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        cbbMaCS = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtDiaDiem = new javax.swing.JTextField();
        cbbMaBH = new javax.swing.JComboBox();
        btnSX = new com.k33ptoo.components.KButton();
        btnTim = new com.k33ptoo.components.KButton();
        btnLamMoi = new com.k33ptoo.components.KButton();
        txtTK = new javax.swing.JTextField();
        btnIn = new com.k33ptoo.components.KButton();

        setPreferredSize(new java.awt.Dimension(920, 490));

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 204, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Thông Tin Biểu Diễn");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_list_36px.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_list_36px.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jtbTTBieuDien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbTTBieuDien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTTBieuDienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbTTBieuDien);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 880, 172));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ngày biểu diễn");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 178, 10));

        txtMaBD.setBackground(new java.awt.Color(153, 204, 255));
        txtMaBD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMaBD.setBorder(null);
        txtMaBD.setOpaque(false);
        kGradientPanel1.add(txtMaBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 180, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mã ca sĩ");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        countBD.setText("Số Lượng Ca Sĩ");
        kGradientPanel1.add(countBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        btnXoaTrang.setText("Xóa Trắng");
        btnXoaTrang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaTrang.setkEndColor(new java.awt.Color(153, 153, 153));
        btnXoaTrang.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnXoaTrang.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnXoaTrang.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        btnXoaTrang.setkStartColor(new java.awt.Color(153, 153, 153));
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnXoaTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 100, 40));

        btnThem.setText("Thêm");
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setkHoverEndColor(new java.awt.Color(0, 204, 102));
        btnThem.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnThem.setkHoverStartColor(new java.awt.Color(0, 102, 102));
        btnThem.setkStartColor(new java.awt.Color(0, 51, 204));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 40));

        btnSua.setText("Sửa");
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnSua.setkHoverStartColor(new java.awt.Color(204, 204, 0));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 100, 40));

        btnXoa.setText("Xóa");
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setkEndColor(new java.awt.Color(255, 51, 0));
        btnXoa.setkHoverEndColor(new java.awt.Color(255, 51, 51));
        btnXoa.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnXoa.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        btnXoa.setkStartColor(new java.awt.Color(255, 51, 51));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 100, 40));

        kGradientPanel1.add(cbbMaCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Mã biểu diễn ");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mã bài hát");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        kGradientPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Địa điểm");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 190, 10));

        txtDiaDiem.setBackground(new java.awt.Color(153, 204, 255));
        txtDiaDiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDiaDiem.setBorder(null);
        txtDiaDiem.setOpaque(false);
        kGradientPanel1.add(txtDiaDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 190, 20));

        kGradientPanel1.add(cbbMaBH, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 100, 30));

        btnSX.setText("Sắp Xếp");
        btnSX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSX.setkEndColor(new java.awt.Color(153, 153, 153));
        btnSX.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnSX.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnSX.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        btnSX.setkStartColor(new java.awt.Color(0, 102, 102));
        btnSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSX, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 100, 40));

        btnTim.setText("Tìm");
        btnTim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTim.setkEndColor(new java.awt.Color(0, 153, 153));
        btnTim.setkHoverEndColor(new java.awt.Color(102, 255, 102));
        btnTim.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnTim.setkHoverStartColor(new java.awt.Color(255, 102, 153));
        btnTim.setkPressedColor(new java.awt.Color(255, 255, 255));
        btnTim.setkStartColor(new java.awt.Color(0, 102, 102));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 70, 30));

        btnLamMoi.setText("Tải Lại");
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLamMoi.setkEndColor(new java.awt.Color(153, 153, 153));
        btnLamMoi.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnLamMoi.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnLamMoi.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        btnLamMoi.setkStartColor(new java.awt.Color(0, 102, 102));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 100, 40));

        txtTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kGradientPanel1.add(txtTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 180, 30));

        btnIn.setText("IN");
        btnIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIn.setkEndColor(new java.awt.Color(0, 153, 153));
        btnIn.setkHoverEndColor(new java.awt.Color(102, 255, 102));
        btnIn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnIn.setkHoverStartColor(new java.awt.Color(255, 102, 153));
        btnIn.setkPressedColor(new java.awt.Color(51, 51, 51));
        btnIn.setkStartColor(new java.awt.Color(0, 102, 102));
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngayBD = dateFormat.format( jDateChooser1.getDate());
        if(this.txtMaBD.getText().length()==0 || this.txtDiaDiem.getText().length()==0)
           JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin","Thông Báo",1);
        else
           
            TTBieuDien.themBD(this.txtMaBD.getText(), this.cbbMaCS.getSelectedItem().toString(),this.cbbMaBH.getSelectedItem().toString(),ngayBD,this.txtDiaDiem.getText());
             loadBD();
    }//GEN-LAST:event_btnThemActionPerformed

    private void jtbTTBieuDienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTTBieuDienMouseClicked
        // TODO add your handling code here:
        try
        {
            int row = this.jtbTTBieuDien.getSelectedRow(); // lấy dòng tại con trỏ chuột
            String IDrow = (this.jtbTTBieuDien.getModel().getValueAt(row, 0)).toString();// Lấy giá trị tại con trỏ chuột theo kiểu string
            //String gioiTinh = (this.jtbCaSi.getModel().getValueAt(row,4)).toString();// Lấy giá trị Giới Tính theo kiểu string
            String sql1 = "select * from thongtinbieudien where MABD=N'"+IDrow+"'";
            ResultSet rs = loadTable.showTextField(sql1);
            DefaultTableModel model = (DefaultTableModel) jtbTTBieuDien.getModel();
            Date ngayBD;
            // đọc dữ liệu tại dòng "IDrow"
            if(rs.next()) // nếu có dữ liệu
            {
                 maBD = rs.getString("MaBD");
                this.txtMaBD.setText(rs.getString("MABD"));
                this.txtDiaDiem.setText(rs.getString("DIADIEM"));
                
                try {
                    ngayBD = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(row, 3).toString());
                    jDateChooser1.setDate(ngayBD);
                } catch (Exception e) {
                    System.out.println(e);
                }
                
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtbTTBieuDienMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(this.txtMaBD.getText().length()==0)
            JOptionPane.showMessageDialog(null,"Vui lòng chọn ca sĩ cần xóa","Thông Báo",1);
        else
       {
            if(JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa ca sĩ "+maBD+" không?","Thông Báo",2)==0)
            {
                CaSi.xoaCS(maBD);
            }
            loadBD();
       }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        // TODO add your handling code here:
        txtMaBD.setText("");
        txtDiaDiem.setText("");
        txtTK.setText("");
        cbbMaBH.setSelectedItem(0);
        cbbMaCS.setSelectedItem(0);
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(this.txtMaBD.getText().length()==0 || this.txtDiaDiem.getText().length()==0 )
            JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin","Thông Báo",1);
        else
       {
            CaSi.suaCS(maBD,this.txtMaBD.getText(), this.txtDiaDiem.getText());
            loadBD();
       }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        loadBD();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM thongtinbieudien ORDER BY MABD"; //lay du lieu
        loadTable.loadData(sql, jtbTTBieuDien);
    }//GEN-LAST:event_btnSXActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if (txtTK.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã biểu diễn cần tìm", "Thông Báo", 1);
        } else {
            String sql = "SELECT * FROM thongtinbieudien WHERE MABD = '" + txtTK.getText() + "'";;

            loadTable.loadData(sql, jtbTTBieuDien);
            this.countBD.setText("Tổng số show diễn: " + this.jtbTTBieuDien.getRowCount());
        }
    }//GEN-LAST:event_btnTimActionPerformed

      public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException ioe) {
            System.out.println(ioe);
        }
    }
    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();

            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("danh sách");
                Row rowCol = sheet.createRow(0);
                for (int i = 0; i < jtbTTBieuDien.getColumnCount(); i++) {
                    Cell cell = rowCol.createCell(i);
                    cell.setCellValue(jtbTTBieuDien.getColumnName(i));
                }
                for (int j = 0; j < jtbTTBieuDien.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 1);
                    for (int k = 0; k < jtbTTBieuDien.getColumnCount(); k++) {
                        Cell cell = row.createCell(k);
                        if (jtbTTBieuDien.getValueAt(j, k) != null) {
                            cell.setCellValue(jtbTTBieuDien.getValueAt(j, k).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());
            } else {
                JOptionPane.showMessageDialog(null, "lỗi");
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
        } catch (IOException io) {
            System.out.println(io);
        }
    }//GEN-LAST:event_btnInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnIn;
    private com.k33ptoo.components.KButton btnLamMoi;
    private com.k33ptoo.components.KButton btnSX;
    private com.k33ptoo.components.KButton btnSua;
    private com.k33ptoo.components.KButton btnThem;
    private com.k33ptoo.components.KButton btnTim;
    private com.k33ptoo.components.KButton btnXoa;
    private com.k33ptoo.components.KButton btnXoaTrang;
    private javax.swing.JComboBox cbbMaBH;
    private javax.swing.JComboBox cbbMaCS;
    public static javax.swing.JLabel countBD;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jtbTTBieuDien;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtDiaDiem;
    private javax.swing.JTextField txtMaBD;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
